version: "2"
services:
    restexample:
        image: restexample:latest
        container_name: restexample
        volumes:
            - ./:/restexample
        ports:
            - 5000:5000
        networks:
            network:
                ipv4_address: 192.168.1.1

    mongodb:
        image: mongo
        ports:
            - 27017:27017
        networks:
            network:
                ipv4_address: 192.168.1.2

    systemtests:
        image: thoom/pyresttest
        volumes:
            - ./tests/:/tests/
        command: "http://192.168.1.1:5000/ system-test.yml"
        networks:
            network:
                ipv4_address: 192.168.1.3

networks:
    network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet:  192.168.1.0/24
                  gateway: 192.168.1.254
