version: "2"
services:
    restexample:
        build: .
        image: restexample:latest
        container_name: restexample
        volumes:
            - ./:/restexample
        ports:
            - 5000:5000
#        links:
#            - mongodb

#    mongodb:
#        image: mongo
#        container_name: mongodb
#        volumes:
#            - mongo-data:/data/db
#        ports:
#            - 27017:27017

volumes:
    mongo-data:
